### ISSUE TITLE
reCAPTCHA MailHide Deprecated

### ISSUE THREAD

**Issue by kurisubrooks** [yosida95/yosida95.com#1]
Your email as visible on your website is no longer visible due to the deprecation of reCAPTCHA's MailHide service.

I found an [alternative](https://mailhide.io/) after a quick google search that maybe you could look into to replace it but if you'd like I can perhaps also submit a Pull Request to rectify the issue.

**Comment by yosida95** [comment]
I have just replaced reCAPTCHA Mailhide with a direct link to my mail address. On yosida95.com, CDN provider Cloudflare provides [Email Address Obfuscation](https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-), which hides mail addresses from malicious bots.

Thank you for letting me know.
